apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-planeteclipse-org
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: planeteclipse-org
  replicas: 1
  template:
    metadata:
      labels:
        app: planeteclipse-org
        environment: staging
    spec:
      containers:
      - name: nginx
        image: eclipsefdn/nginx:stable-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: planet-www
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            cpu: '2'
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
      - name: planet-venus
        image: eclipsefdn/planet-venus:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: planet-www
          mountPath: /var/planet/www
        - name: planet-cache
          mountPath: /var/planet/cache
        - name: planet-config
          mountPath: /var/planet/config
        resources:
          limits:
            cpu: '2'
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 512Mi
      volumes:
      - name: planet-www
        emptyDir: {}
      - name: planet-cache
        emptyDir: {}
      - name: planet-config
        emptyDir: {}
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: planeteclipse-org
  namespace: webapps
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: planeteclipse-org
    environment: staging
---
apiVersion: "route.openshift.io/v1"
kind: "Route"
metadata:
  name: planeteclipse-org
  namespace: webapps
  annotations:
    haproxy.router.openshift.io/timeout: 20s
spec:
  host: "ci-staging.eclipse.org"
  path: "/planet"
  port:
    targetPort: "http"
  tls:
    insecureEdgeTerminationPolicy: "Redirect"
    termination: "edge"
  to:
    kind: "Service"
    name: planeteclipse-org
    weight: 100
